name: Backup
on:
  pull_request:
    branches:
      - master
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  backup_repo:
    runs-on: windows-latest
    steps:
      - name: Create Branch
        uses: Vent-Finance/branch_creator@v1.0.0
        env:
         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
           branch: release
