name: Backup
on:
  pull_request:
    branches:
      - master
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  backup_repo:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
           branch: release-candidate1
